---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp kontak-page.html $DEPLOYPATH
    - /bin/cp photo-page.html $DEPLOYPATH
    - /bin/cp post-page.html $DEPLOYPATH
    - /bin/cp video-page.html $DEPLOYPATH
    - /bin/cp vr-page.html $DEPLOYPATH
    